### ISSUE TITLE
apply.paramset: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by vpalvesalan** [braverock/quantstrat#92] opened 2018-07-01 21:34 UTC
I am getting the following err on apply.paramset():

> Error in if (nrow(results$tradeStats) > 0 && nrow(results$tradeStats) ==  : 
  missing value where TRUE/FALSE needed

```
#Load libraries
library(quantstrat)
library(lubridate)
library(dplyr)

#Run multi cores
library(parallel)
library(doMC)
registerDoMC(cores = detectCores())

#source functions
source("home/alan/R finance/chartFunction.R")

#Set currency and timezone
Sys.setenv(TZ='UTC')
currency("BRL")

#set paramenters to download data and for setting up account
start_date <- ymd("2017-01-01")
end_date <- ymd("2018-06-28")
init_date <- ymd("2016-12-31")
init_equity <- "6000"
stock_string <- "BBDC4.SA"

#Download and clean data
getSymbols(Symbols = stock_string, src = "yahoo", from = start_date, to = end_date, adjust =TRUE)
i <- get(stock_string)[,4]!=0
assign(stock_string, get(stock_string)[i])

#Define setting for strategy
portfolio.st <- "basic_portfolio"
account.st <- "basic_account"
strategy.st <- "OBV_strat"

#Clear hipothetical previous runs
rm.strat(portfolio.st)
rm.strat(account.st)

#Strategy setup
stock(stock_string, currency = "BRL", multiplier = 1) #Define currency for stock
initPortf(name = portfolio.st, symbols = stock_string, initDate = init_date)
initAcct(name = account.st, portfolios = portfolio.st, initDate = init_date, initEq =init_equity)
initOrders(portfolio.st, stock_string, init_date)
strategy(strategy.st, store = TRUE)

#Add indicators
nn=12
sma_string <- paste0("sma",nn,"_obv")
add.indicator(strategy.st, name = "OBV", arguments = list(price = quote(Cl(mktdata)), volume = quote(Vo(mktdata))), label = "obv")
add.indicator(strategy.st, name = "SMA", arguments = list(x = quote(mktdata$obv), n=nn), label =sma_string)

#Add Signals
add.signal(strategy.st, name = "sigCrossover", arguments = list(columns = c("obv", sma_string), relationship = "gt"), label = "long")
add.signal(strategy.st, name = "sigCrossover", arguments = list(columns = c("obv", sma_string), relationship = "lt"), label = "short")

#Add rules for entering positions
#enter long position
add.rule(strategy.st, 
         name = "ruleSignal", 
         arguments = list(sigcol = "long",
                          sigval = TRUE,
                          orderqty = 100,
                          ordertype = "market",
                          orderside = "long",
                          #threshold = 0.0005,
                          #prefer = "Open",
                          TxnFees = -.8,
                          replace = FALSE),
         type = "enter",
         label = "EnterLong")

#enter short position
add.rule(strategy.st,
         name = "ruleSignal",
         arguments = list(sigcol = "short",
                          sigval = TRUE,
                          orderqty = -100,
                          ordertype = "market",
                          #threshold = -0.0005,
                          orderside = "short", 
                          replace = FALSE, 
                          TxnFees = -.8), 
                          #prefer = "Open"),
         type = "enter",
         label = "EnterShort")

#Add rules for exiting opened postions
#exit long positions
add.rule(strategy.st, 
         name = "ruleSignal", 
         arguments = list(sigcol = "short", 
                          sigval = TRUE, 
                          orderside = "long", 
                          ordertype = "market", 
                          orderqty = "all", 
                          TxnFees = -.8, 
                          replace = TRUE), 
         type = "exit", 
         label = "ExitLong")

#exit short positions
add.rule(strategy.st, 
         name = "ruleSignal", 
         arguments = list(sigcol = "long", 
                          sigval = TRUE, 
                          orderside = "short", 
                          ordertype = "market", 
                          orderqty = "all", 
                          TxnFees = -.8, 
                          replace = TRUE), 
         type = "exit", 
         label = "ExitShort")

#Add Distribution
.nSMA <- c(4,8,12,16,20,26,32)
add.distribution(strategy.st,
                 paramset.label = "SMA",
                 component.type = "indicator",
                 component.label = sma_string,
                 variable = list(n = .nSMA),
                 label = "nSMA")

#Apply paramset
apply.paramset(strategy.st,
               paramset.label = "SMA",
               portfolio.st = portfolio.st,
               account.st = account.st)
```
>Error in if (nrow(results$tradeStats) > 0 && nrow(results$tradeStats) ==  : 
  missing value where TRUE/FALSE needed``` 

```
sessionInfo()

```
>R version 3.4.4 (2018-03-15) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 18.04 LTS  Matrix products: default BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1 LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1  locale:  [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C                [3] LC_TIME=pt_BR.UTF-8        LC_COLLATE=en_US.UTF-8      [5] LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=en_US.UTF-8     [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                   [9] LC_ADDRESS=C               LC_TELEPHONE=C             [11] LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] parallel  stats     graphics  grDevices utils     datasets  [7] methods   base       other attached packages:  [1] doMC_1.3.5                   iterators_1.0.9               [3] dplyr_0.7.5                  lubridate_1.7.4               [5] quantstrat_0.14.6            foreach_1.4.4                 [7] blotter_0.14.2               PerformanceAnalytics_1.5.2.2  [9] FinancialInstrument_1.3.0    quantmod_0.4-13              [11] TTR_0.23-3                   xts_0.10-2                   [13] zoo_1.8-2                     loaded via a namespace (and not attached):  [1] Rcpp_0.12.17     bindr_0.1.1      magrittr_1.5      [4] MASS_7.3-49      tidyselect_0.2.4 lattice_0.20-35   [7] R6_2.2.2         rlang_0.2.0      quadprog_1.5-5   [10] stringr_1.3.1    tools_3.4.4      grid_3.4.4       [13] yaml_2.1.19      assertthat_0.2.0 tibble_1.4.2     [16] bindrcpp_0.2.2   purrr_0.2.4      codetools_0.2-15 [19] curl_3.2         glue_1.2.0       stringi_1.2.2    [22] pillar_1.2.2     compiler_3.4.4   boot_1.3-20      [25] pkgconfig_2.0.1

**Comment by N0talent** [comment] 2018-07-05 08:18
This not a Bug imho.
the "problem" is that you are adding a Costum Funtion.  `source("home/alan/R finance/chartFunction.R")`
and im assuming that you did not configurer your parallel-computing correctly. 
under Windows i need to add all functions into my cluster using: 

```
> cl <- makeCluster(4L)
> registerDoParallel(cl)
> clusterExport(cl, <all functions and values needed for calculation>)
```

**Comment by JimBimJimBim** [comment] 2018-09-27 13:38
I ran into exactly the same problem with walk.forward().
****[1] "=== training smaOPT on 2006-01-03/2009-11-30"
Error in if (nrow(results$tradeStats) > 0 && nrow(results$tradeStats) ==  :** 
  missing value where TRUE/FALSE needed**
I used advice from the previous post, but it did not help.
library(doParallel)
cl <- makeCluster(2)
registerDoParallel(cl)
clusterExport(cl, c('DVO', 'osMaxDollar'))
"DVO" and "osMaxDollar" are custom functions.  Does anyone know what the problem is?

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251   
[3] LC_MONETARY=Russian_Russia.1251 LC_NUMERIC=C                   
[5] LC_TIME=Russian_Russia.1251    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] doParallel_1.0.14          iterators_1.0.10          
 [3] quantstrat_0.14.6          foreach_1.4.4             
 [5] blotter_0.14.2             PerformanceAnalytics_1.5.2
 [7] FinancialInstrument_1.3.1  quantmod_0.4-13           
 [9] TTR_0.23-4                 xts_0.11-1                
[11] zoo_1.8-4                 

loaded via a namespace (and not attached):
 [1] quadprog_1.5-5   lattice_0.20-35  codetools_0.2-15 MASS_7.3-47     
 [5] grid_3.4.0       curl_3.2         boot_1.3-19      tools_3.4.0     
 [9] yaml_2.2.0       compiler_3.4.0

**Comment by JimBimJimBim** [comment] 2018-09-27 13:59
It looks like an error in **paramsets.R**
**create foreach object**
fe <- foreach( param.combo=iter(param.combos,by='row')
               ,.verbose=verbose, .errorhandling='pass'
               ,.packages=c('quantstrat', packages)
               ,.combine=combine.results
               , .multicombine=TRUE
               , .maxcombine=max(2,nrow(param.combos))
               ,.export=c(env.functions, symbols)
               , ...

_make sure we preserve the param combo name in cumPL_

**if(nrow(results$tradeStats)>0 && nrow(results$tradeStats)==ncol(results$cumPL)){
  colnames(results$cumPL) <- rownames(results$tradeStats)
}**

**Comment by braverock** [comment] 2018-10-03 13:14
@JimBimJimBim Thanks for looking into this!

It seems that it would be useful to do more testing on the parameters when they are parsed, and see if we can locate all the referenced columns.  This won't be perfect, as indicator or signal functions are arbitrary R code, and may have passthrough or implied parameters.  But anything that quantstrat controls, like `component.label`, should be checkable.

**Comment by jaymon0703** [comment] 2019-06-08 11:20
hi @vpalvesalan do you still get this error on the latest version, 0.16.1?

**Comment by jaymon0703** [comment] 2020-07-06 18:38
Closing this issue, if still an issue please feel free to re-open @vpalvesalan.

**Closed by jaymon0703** 2020-07-06 18:38 UTC
