### ISSUE TITLE
Speed up rebalancing

### ISSUE THREAD

**Issue by granstubbe** [braverock/quantstrat#69] opened 2017-08-29 14:29 UTC
I'm running backtests with the applyStrategy.rebalancing() and they keep taking really long, this simple strategy:

```
library(quantstrat)
library(PerformanceAnalytics)
library(FinancialInstrument)
library(TTR)
#Simple SMA strategy where buy if Close >= nSMA and sell if opposite.
#Rebalancing between each month and reinvesting 100% of sold equities divided by the number
#of unique symbols

nSMA = 10

Sys.setenv(TZ = "UTC")

currency("USD")
symbols <- c("XLY", "XLE", "AGG", "IVV")

initEq <- 1000000
strategy.st <- portfolio.st <- account.st <- "Simple_SMA"
initDate <- "1900-01-01"
from="2009-01-01"
to="2017-07-01"

# get data for the symbols
getSymbols(symbols, from=from, to=to, adjust = T,src = "yahoo")

stock(symbols, currency="USD",multiplier = 1)

#Only keep monthly data
for(i in 1:length(symbols)) {
  x <- get(symbols[i])
  x <- to.monthly(x,indexAt='lastof',drop.time=T)
  indexFormat(x) <- '%Y-%m-%d'
  colnames(x) <- gsub("x",symbols[i],colnames(x))
  assign(symbols[i],x)
}

# remove variables
rm.strat(strategy.st)

initPortf(portfolio.st, symbols=symbols, initDate=initDate, currency='USD')
initAcct(account.st, portfolios=portfolio.st, initDate=initDate, currency='USD',initEq=initEq)
initOrders(portfolio.st, initDate=initDate)
strategy(strategy.st, store=TRUE)

#set intial position limits
posval<-initEq/length(symbols)

for(symbol in symbols){
  pos<-round((posval/first(getPrice(get(symbol)))[,1]),-2)
  addPosLimit(portfolio.st, symbol, from, maxpos=pos, minpos=-pos)
}

add.indicator(strategy.st, name="SMA",
              arguments=list(x=quote(Cl(mktdata)), n=nSMA),
              label="sma")

add.signal(strategy=strategy.st, name="sigCrossover", 
           arguments=list(column=c("Close","sma"), 
                          relationship="gte", cross=TRUE), 
           label="longEntry")

add.signal(strategy=strategy.st, name="sigCrossover", 
           arguments=list(column=c("Close","sma"), 
                          relationship="lt", cross=TRUE), 
           label="longExit")

# add buy rule with rulePctEquity
add.rule(strategy=strategy.st, name='ruleSignal', 
         arguments = list(sigcol="longEntry", sigval=TRUE, 
                          osFUN='osMaxPos',orderqty = 100000, ordertype='market', 
                          orderside='long', pricemethod='market', 
                          replace=F), 
         type='enter', path.dep=TRUE)

add.rule(strategy.st, 'rulePctEquity',
                 arguments=list(rebalance_on='months',
                                  trade.percent=1/length(symbols),
                                  refprice=quote(last(getPrice(mktdata)[paste('::',curIndex,sep='')])),
                                  digits=0
                                  ),
         type='rebalance',
         label='rebalance'
        )

# add exit rule
add.rule(strategy = strategy.st, name='ruleSignal', 
         arguments = list(sigcol="longExit", sigval=TRUE, 
                          orderqty='all', ordertype='market', 
                          orderside='long', pricemethod='market', 
                          replace=F), 
         type='exit', path.dep=TRUE)

print("setup completed")

# apply the strategy to the portfolio
start_t <- Sys.time()
out <- try(applyStrategy.rebalancing(strategy=strategy.st, portfolios=portfolio.st))
end_t <- Sys.time()
print(end_t-start_t)

#set up analytics
updatePortf(portfolio.st)
dateRange <- time(getPortfolio(portfolio.st)$summary)[-1]
updateAcct(portfolio.st,dateRange)
updateEndEq(account.st)
# update account
updateAcct(account.st)
```

It takes ~1 minute to compute vs 0.6 seconds if I only run applyStrategy() which doesn't rebalance.

I really like the rebalancing feature, but it takes so long. Is there any way to improve the performance and speed it up while still rebalancing? Other than a more powerful computer...

**Comment by braverock** [comment] 2017-08-29 17:03
No.

You're basically forcing quantstrat to evaluate your rebalance rules on every observation.  As stated in multiple places in the documentation, the speed of running a backtest will be roughly linearly dependent with the number of rule calculations.

Your example makes 42 transactions for me, and runs in 36.4 seconds.

Your data has 102 rows each for 4 instruments, so roughly 10x the number of signals.

So I would expect the execution time to be approximately an order of magnitude larger even if the rule function did nothing at all.

rulePctEquity is doing a lot more than nothing.  It updates the portfolio every time it is called.  This is not an efficient calculation.  In general, you would only update the portfolio once at the end of the backtest.

If you really *must* rebalance this often, then you basically have three options:
- rebalance less frequently. your model makes reallyno significant position size changes.  you're not learning anything from minor changes to pretend money.
- write a more efficient rebalancing function. you could easily call getTxns, and add up realized P&L for each instrument, and calcualte unrealized P&L from your position and the average cost of that position.  This would be more efficient than calling updatePortf
- get a faster computer 

We run backtests on tick data, and a large backtest can easily run several hours on multiple cores.  your timings seem like more of a minor annoyance in comparison

**Comment by granstubbe** [comment] 2017-08-29 18:10
I thank you for your answer, I've tried to search but I think my focus was too narrow. 

Haha yeah, it's a minor inconvenience in this simple example, but changing to a fairly simple momentum based strategy with more symbols, and adding a few parameters and doing an optimisation made my machine warm enough to heat my coffee all morning. 

I'll go through what you've written and I hope someone else also finds some use of this in the future :)

**Comment by braverock** [comment] 2017-08-29 18:53
You mentioned heat and parameter optimization.

One thing I discovered while travelling this summer was that a laptop is really not cut out for this type of work.

I have a recent 4-core/8-thread i7 laptop with 16GB of RAM that I only use when travelling. I was running a parameter optimization example for my UW class.  It takes over an hour on my laptop, and less than two minutes on one of my research workstations.  I realized that the issue is heat throttling on the laptop processor.  My laptop, when it overheats, throttles back each core, clearly by a lot.  You may be seeing similar issues.

**Comment by braverock** [comment] 2018-06-05 12:45
Recent changes to parameter optimization have resulted in 12-20x+ speedups.  We've decreased the number of copies, and made physical I/O optional.

I would suggest that you look at the R/Finance 2018 presentation markdown in the vignettes directory, and see if it solves your issues.  I'm going to close this issue, as I think we've done about everything we can to speed up parameter optimization and walk forward for now.

**Closed by braverock** 2018-06-05 12:45 UTC
Labels: feature request

**Comment by herrmol** [comment] 2020-04-11 12:25
Hello Brian, this was the most recent post I found related to using "rulePctEquity" and "reblance", therefore I post my question here. It is not strictly related to speed but very similar.

I build the same strategy and other strategies that use "rulePctEquity". When I look at the getTxns() and getOrderBook() outputs, I never never find that the "rulePctEquity" was fired or applied. I have the label set to "rebalance" so I would expect to find some rebalancing transaction at the end of the month (if rebalance_on set to months).
I also calculated the equity (initial plus P/L) and the equity is never balanced.

Can you give me a hint where I find that the balancing rules were applied after running the strategy?
Cheers

**Comment by braverock** [comment] 2020-04-11 17:46
> Hello Brian, this was the most recent post I found related to using "rulePctEquity" and "reblance", therefore I post my question here. It is not strictly related to speed but very similar.
> 
> I build the same strategy and other strategies that use "rulePctEquity". When I look at the getTxns() and getOrderBook() outputs, I never never find that the "rulePctEquity" was fired or applied. I have the label set to "rebalance" so I would expect to find some rebalancing transaction at the end of the month (if rebalance_on set to months).
> I also calculated the equity (initial plus P/L) and the equity is never balanced.
> 
> Can you give me a hint where I find that the balancing rules were applied after running the strategy?
> Cheers

This really has nothing to do with this ticket.  

rules of type 'rebalance' will fire periodically as defined in the rule.  rebalancing rules will generate transactions just like any other execution rule.

See demo scripts `macdRebalancing` and `faber_rebal` for examples.  If the demo scripts don't solve your problem, please construct a minimal, reproducible, example, and open a new ticket focused specifically on the re-balancing problem you are having.
