### ISSUE TITLE
Error when running walk.forward over a short testing period

### ISSUE THREAD

**Issue by edward-wilson** [braverock/quantstrat#45] opened 2016-07-28 12:37 UTC
The extended GBPUSD data used in the creation of the Luxor Demo includes (at least) an erroneous date (2002/10/27) with only 1 observation which causes an issue if you run the walk.forward function with a test period of 1 day. It tries to run the signal/indicator calculations with a look back period of "n" over this one observation which raises an error. I can also foresee this being an issue when testing longer signal periods on instruments like Crude where they have only a few trading hours on Sunday evenings (UTC). 

I solved this by cleaning the data pre-WFA, ensuring only days with a full amount of observations were used, but this is far from optimal!

Traceback:

`8: stop("Invalid 'n'")`
`7: runSum(x, n)`
`6: runMean(x, n)`
`5: (function (x, n = 10, ...) `
   `{`
     `  ma <- runMean(x, n)`
    `   if (!is.null(dim(ma))) {`
       `colnames(ma) <- "SMA"`
 `  }`
  ` return(ma)`
 `  })(x = Cl(mktdata)[, 1], n = 25)`
`4: do.call(indFun, .formals)`
`3: applyIndicators(strategy = strategy, mktdata = mktdata, parameters = parameters, `
  ` ...)`
`2: applyStrategy(strategy, portfolios = portfolio.st, mktdata = symbol[testing.timespan]) at` `walk.forward.R#122`
`1: walk.forward(strategy.st, paramset.label = "WFA", portfolio.st = portfolio.st, `
  ` account.st = account.st, period = "days", k.training = 3, `
  ` k.testing = 1, obj.func = my.obj.func, obj.args = list(x = quote(result$apply.paramset)), `
  ` audit.prefix = "wfa", anchored = FALSE, verbose = TRUE)`

**Comment by joshuaulrich** [comment] 2016-07-28 12:47
Closing as duplicate of #34.

**Closed by joshuaulrich** 2016-07-28 12:47 UTC
